---
- name: Block to execute python script to fetch data from Elasticsearch
  block:
  - name: Create output directories if they don't exist
    ansible.builtin.file:
      path: "{{ playbook_dir }}/roles/files/{{ item }}"
      state: directory
      mode: '0755'
    loop:
    - "temp"
    - "output"

  - name: Execute python script to fetch data from Elasticsearch
    ansible.builtin.command:
      argv:
      - python3
      - "{{ playbook_dir }}/roles/files/fetch_data.py"
      - "--es-url"
      - "{{ es_url }}"
      - "--es-service-id"
      - "{{ es_service_id }}"
      - "--es-password"
      - "{{ es_service_id_password }}"
      - "--index-name"
      - "{{ server_compliance_metrics_index }}"
      - "--app-codes"
      - "{{ app_codes }}"
    environment:
      PYTHONPATH: "{{ playbook_dir }}/roles/files"
    register: fetch_data_response

  - name: Debug fetch data response
    ansible.builtin.debug:
      msg: "{{ fetch_data_response.stdout }}"

  rescue:
  - name: Failed to fetch data from Elasticsearch
    ansible.builtin.debug:
      msg: "Failed to fetch data from Elasticsearch. Please check the logs for more details."

  - name: Fail playbook - fetching data from Elasticsearch failed
    ansible.builtin.fail:
      msg: Fail playbook - fetching data from Elasticsearch failed
