---
- name: Block to execute python script to fetch data from Elasticsearch
  block:
  - name: Create output directories if they don't exist
    ansible.builtin.file:
      path: "{{ playbook_dir }}/roles/files/{{ item }}"
      state: directory
      mode: '0755'
    loop:
    - "temp"
    - "output"

  - name: Set app_codes as a list if it's a string
    ansible.builtin.set_fact:
      app_codes_list: "{{ [app_codes] if app_codes is string else app_codes }}"

  - name: Display app_codes variable
    ansible.builtin.debug:
      var: app_codes_list

  - name: Execute python script to fetch data from Elasticsearch
    ansible.builtin.shell:
      cmd: >
        python3 {{ playbook_dir }}/roles/files/fetch_data.py  --es-url "{{ es_url }}"  --es-service-id "{{ es_service_id }}"  --es-password "{{ es_service_id_password }}"  --index-name "{{ server_compliance_metrics_index }}"  --app-codes {% for code in app_codes_list %}"{{ code }}" {% endfor %}
      chdir: "{{ playbook_dir }}/roles/files"
    environment:
      PYTHONPATH: "{{ playbook_dir }}/roles/files"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    register: fetch_data_response

  - name: Debug fetch data response
    ansible.builtin.debug:
      msg: "{{ fetch_data_response.stdout }}"

  rescue:
  - name: Failed to fetch data from Elasticsearch
    ansible.builtin.debug:
      msg: "Failed to fetch data from Elasticsearch. Please check the logs for more details."

  - name: Fail playbook - fetching data from Elasticsearch failed
    ansible.builtin.fail:
      msg: Fail playbook - fetching data from Elasticsearch failed
