---
- name: Assign secrets to dedicated variables
  ansible.builtin.set_fact:
    es_service_id: "SATU0SRVECEWRITE"
    es_service_id_password: "R4@.iE@GmdVMp3"
  no_log: true

- name: Assign extra vars to dedicated variables
  ansible.builtin.set_fact:
    to: "feyi.sodipo@rbc.com"
    es_url: "https://e87a6cd02ed34b0b844d64cc7d8c41a9.ece.saifg.rbc.com:9243"
    server_compliance_metrics_index: "atu0-server-compliance-metrics"
    app_codes: "ATU0"

- name: Installing elastic module
  ansible.builtin.pip:
    name: elasticsearch
    state: present

- name: Fetch data from Elasticsearch
  ansible.builtin.include_tasks: fetch_data.yml

- name: Process data and generate reports
  ansible.builtin.include_tasks: process_data.yml

- name: Loop through app codes and notify app custodian
  block:
  - name: Get custodian email for appcode
    ansible.builtin.set_fact:
      custodian_email: "feyi.sodipo@rbc.com"

  - name: Send notification upon data successfully indexed
    ansible.builtin.debug:
      msg: |
        email_to: feyi.sodipo@rbc.com
        subject: ATU0 - Server Compliance Overview
        body:
          Hello,
          The data has been processed and indexed successfully.
