---
- name: Block to execute python script to process data and generate reports
  block:
  - name: Execute python script to process data and generate reports
    ansible.builtin.shell:
      cmd: >
        python3 {{ playbook_dir }}/roles/files/process_data.py --input-dir "{{ playbook_dir }}/roles/files" --output-dir "{{ playbook_dir }}/roles/files/output"
      chdir: "{{ playbook_dir }}/roles/files"
    environment:
      PYTHONPATH: "{{ playbook_dir }}/roles/files"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    register: process_data_response

  - name: Debug process data response
    ansible.builtin.debug:
      msg: "{{ process_data_response.stdout }}"

  rescue:
  - name: Failed to process data and generate reports
    ansible.builtin.debug:
      msg: "Failed to process data and generate reports. Please check the logs for more details."

  - name: Fail playbook - processing data and generating reports failed
    ansible.builtin.fail:
      msg: Fail playbook - processing data and generating reports failed
