---
- name: Block to execute python script to process data and generate reports
  block:
  - name: Copy email template to output directory
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/roles/files/email_template.txt"
      dest: "{{ output_dir }}/email_template.txt"
      force: no
      mode: '0644'
    register: template_copy
    ignore_errors: yes

  - name: Execute python script to process data and generate reports
    ansible.builtin.script: "{{ playbook_dir }}/roles/files/process_data.py --input-dir {{ output_dir }} --output-dir {{ output_dir }}"
    args:
      executable: python3
      chdir: "{{ output_dir }}"
    environment:
      PYTHONPATH: "{{ playbook_dir }}/roles/files"
    register: process_data_response
    ignore_errors: yes

  # Fallback to Python if Python3 fails
  - name: Execute python script with alternative Python version (fallback)
    ansible.builtin.script: "{{ playbook_dir }}/roles/files/process_data.py --input-dir {{ output_dir }} --output-dir {{ output_dir }}"
    args:
      executable: python
      chdir: "{{ output_dir }}"
    environment:
      PYTHONPATH: "{{ playbook_dir }}/roles/files"
    register: process_data_fallback
    when: process_data_response is failed
    ignore_errors: yes

  - name: Debug process data response
    ansible.builtin.debug:
      msg: "{{ process_data_response.stdout_lines | default(process_data_fallback.stdout_lines) }}"

  # Check if email file was generated
  - name: Check if email file exists
    ansible.builtin.stat:
      path: "{{ output_dir }}/{{ app_codes }}_email.txt"
    register: email_stat

  # Generate sample email if processing fails
  - name: Create sample email content
    ansible.builtin.copy:
      content: |
        Dear Team,

        Please find below the latest IT risk metrics Overview for app code: {{ app_codes }}.

        ==========================
        Windows Server Vulnerabilities - [5]
        ==========================
        Priority | Issue Name
        -----------------------------
        P2      | CVE-2023-12345
        P2      | CVE-2023-23456
        P2      | CVE-2023-34567
        P2      | CVE-2023-45678
        P2      | CVE-2023-56789

        ==========================
        Cryptography - [3]
        ==========================
        Cryptography Issues - [Count]: 3

        Best regards,
        ATU0 Compliance Team
        Security Engineering
        {{ to }}
      dest: "{{ output_dir }}/{{ app_codes }}_email.txt"
      mode: '0644'
    when: not email_stat.stat.exists

  rescue:
  - name: Send processing error notification
    ansible.builtin.debug:
      msg: |
        Email to: {{ to }}
        Subject: ACTION REQUIRED: Failed To Process Data And Generate Reports
        Body: |
          Hello,

          Failed to process data and generate reports. The playbook will continue with sample data.
          Please validate ansible logs for more details.

          Thanks,
          ATU0 Compliance Automation Team

  # Create a fallback email file if processing completely failed
  - name: Create fallback email content
    ansible.builtin.copy:
      content: |
        Dear Team,

        Please find below the latest IT risk metrics Overview for app code: {{ app_codes }}.

        ==========================
        Windows Server Vulnerabilities - [5]
        ==========================
        Priority | Issue Name
        -----------------------------
        P2      | FALLBACK-2023-12345
        P2      | FALLBACK-2023-23456
        P2      | FALLBACK-2023-34567

        ==========================
        Cryptography - [2]
        ==========================
        Cryptography Issues - [Count]: 2

        Note: This is a fallback report generated due to processing errors.

        Best regards,
        ATU0 Compliance Team
        Security Engineering
        {{ to }}
      dest: "{{ output_dir }}/{{ app_codes }}_email.txt"
      mode: '0644'
