---
- name: Verify required variables
  ansible.builtin.assert:
    that:
    - vault_path is defined
    - raw_data_file is defined
    - output_dir is defined
    - role_path is defined
    - survey_appcode is defined
    - vault_env is defined
    fail_msg: "Missing required variables. Please ensure all required variables are defined"

# Define file paths and environment variables
- name: Set file path and environment variables
  set_fact:
    processed_report: "{{ output_dir }}/vulnerability_report_processed.json"
    email_content_file: "{{ output_dir }}/email_content.txt"
    email_template: "{{ role_path }}/files/email_template.txt"
    app_code: "{{ survey_appcode | upper }}"
    vault_environment: "{{ vault_env }}"
    current_issue_type: "{{ issue_type }}"

# Ensure output directory exists
- name: Ensure output directory exists
  file:
    path: "{{ output_dir }}"
    state: directory
    mode: '0755'

- name: Check if processed report exists
  stat:
    path: "{{ processed_report }}"
  register: report_stat

- name: Check if email content exists
  stat:
    path: "{{ email_content_file }}"
  register: email_stat

- name: Load email content
  slurp:
    src: "{{ email_content_file }}"
  register: email_content
  when: email_stat.stat.exists

- name: Load report data for email
  slurp:
    src: "{{ processed_report }}"
  register: report_data
  when: report_stat.stat.exists

- name: Display direct report summary (like in process_data.yml)
  debug:
    msg:
    - "Report Summary (Direct Access):"
    - "Total results: {{ (report_data.content | b64decode | from_json).summary.total_vulnerabilities }}"
    - "High severity issues: {{ (report_data.content | b64decode | from_json).summary.high_severity_count }}"
    - "Application codes: {{ (report_data.content | b64decode | from_json).summary.app_codes | join(', ') }}"
    - "Issue types found: {{ (report_data.content | b64decode | from_json).summary.issue_types | join(', ') }}"
    - "Issue type queried: {{ issue_type }}"
  when: report_stat.stat.exists

- name: Set report variables for email
  set_fact:
    report_json: "{{ report_data.content | b64decode | from_json }}"
    email_body: "{{ email_content.content | b64decode }}"
    report_date: "{{ ansible_date_time.date }}"
    total_vulnerabilities: "{{ report_json.summary.total_vulnerabilities | int }}"
    start_date: "{{ report_json.summary.start_date }}"
    end_date: "{{ report_json.summary.end_date }}"
    high_severity_count: "{{ report_json.summary.high_severity_count | int }}"
  when: report_stat.stat.exists and email_stat.stat.exists

# Get email recipient from vault with fallback
- name: Get email recipient from vault
  block:
  - name: Try vault lookup
    set_fact:
      email_recipient: "{{ lookup('vars', 'vault')[vault_environment]['vault_extravars']['to'] }}"
    when: vault is defined
  rescue:
  - name: Use default recipient on vault lookup failure
    set_fact:
      email_recipient: "{{ to }}"

# Debug output to show what's in the report
- name: Debug report values
  debug:
    msg: |
      Report Values:
      - report_json.summary: {{ report_json.summary }}
      - report_json.summary.issue_types: {{ report_json.summary.issue_types }}
      - current_issue_type: {{ current_issue_type }}
      - email_body excerpt: {{ email_body | truncate(100) }}
  when: report_stat.stat.exists and email_stat.stat.exists

- name: Send vulnerability report notification
  ansible.builtin.include_role:
    name: rbc_sfmo.components.email
  vars:
    appcode: "{{ app_code }}"
    email_to: "{{ email_recipient }}"
    email_cc: []
    email_subject: "Issue Report - {{ report_date }} - {{ app_code }}"
    issue_types: "{{ report_json.summary.issue_types | join(', ') }}"
    email_body: "{{ email_body }}"
    email_env_domain: "{{ ansible_domain }}"
    email_attachments:
    - "{{ processed_report }}"
    register: email_result

- name: Log email notification
  debug:
    msg: |
      Email notification details:
      - Sent to: {{ email_recipient }}
      - App Code: {{ app_code }}
      - Environment: {{ vault_environment | upper }}
      - Total issues: {{ total_vulnerabilities }}
      - High severity count: {{ high_severity_count }}
      - Issue Type: {{ current_issue_type }}
      - Actual issue types from report: {{ report_json.summary.issue_types | join(', ') }}
  when: report_stat.stat.exists and email_stat.stat.exists
