---
# Ansible playbook to send notification emails to custodians about vulnerabilities
# This playbook sends emails using the processed report data

# Ensure required variables are defined
- name: Verify required variables
  ansible.builtin.assert:
    that:
    - vault_path is defined
    - raw_data_file is defined
    - output_dir is defined
    - role_path is defined
    - survey_appcode is defined
    - vault_env is defined
    fail_msg: "Missing required variables. Please ensure all required variables are defined"

# Define file paths and environment variables
- name: Set file path and environment variables
  set_fact:
    processed_report: "{{ output_dir }}/vulnerability_report_processed.json"
    email_content_file: "{{ output_dir }}/email_content.txt"
    email_template: "{{ role_path }}/files/email_template.txt"
    app_code: "{{ survey_appcode | upper }}"
    vault_environment: "{{ vault_env | default('DEV') }}"
    current_issue_type: "{{ issue_type | default('Vulnerability') }}"

# Ensure output directory exists
- name: Ensure output directory exists
  file:
    path: "{{ output_dir }}"
    state: directory
    mode: '0755'

- name: Check if processed report exists
  stat:
    path: "{{ processed_report }}"
  register: report_stat

- name: Check if email content exists
  stat:
    path: "{{ email_content_file }}"
  register: email_stat

- name: Load email content
  slurp:
    src: "{{ email_content_file }}"
  register: email_content
  when: email_stat.stat.exists

- name: Load report data for email
  slurp:
    src: "{{ processed_report }}"
  register: report_data
  when: report_stat.stat.exists

- name: Set report variables for email
  set_fact:
    report_json: "{{ report_data.content | b64decode | from_json }}"
    email_body: "{{ email_content.content | b64decode }}"
    report_date: "{{ ansible_date_time.date }}"
    total_vulnerabilities: "{{ report_json.summary.total_vulnerabilities | default(0) }}"
    start_date: "{{ report_json.summary.start_date | default(ansible_date_time.date) }}"
    end_date: "{{ report_json.summary.end_date | default(ansible_date_time.date) }}"
    high_severity_count: "{{ report_json.summary.high_severity_count | default(0) }}"
  when: report_stat.stat.exists and email_stat.stat.exists

# Get email recipient from vault with fallback
- name: Get email recipient from vault
  block:
  - name: Try vault lookup
    set_fact:
      email_recipient: "{{ lookup('vars', 'vault')[vault_environment]['vault_extravars']['to'] }}"
    when: vault is defined
  rescue:
  - name: Use default recipient on vault lookup failure
    set_fact:
      email_recipient: "{{ to }}"

- name: Send vulnerability report notification
  ansible.builtin.include_role:
    name: rbc_sfmo.components.email
  vars:
    appcode: "{{ app_code }}"
    email_to: "{{ email_recipient }}"
    email_cc: []
    email_subject: "{{ current_issue_type }} Report - {{ report_date }} - {{ app_code }}"
    issue_types: "{{ current_issue_type }}"
    email_body: |
      Hello Team,

      The automated {{ current_issue_type }} scan for application code {{ app_code }} has been completed.

      Summary:
      - Total {{ current_issue_type }} found: {{ total_vulnerabilities }}
      - Time period: {{ start_date }} to {{ end_date }}
      - Application code: {{ app_code }}
      - Environment: {{ vault_environment | upper }}

      {% if high_severity_count > 0 %}
      ATTENTION: {{ high_severity_count }} high severity issues were detected that require immediate action.
      {% endif %}

      Please review the attached report for detailed information about the {{ current_issue_type }} issues.

      The report includes:
      - Issue type: {{ (report_json.summary.issue_types | join(', ')) if report_json.summary.issue_types is defined and report_json.summary.issue_types | length > 0 else current_issue_type }}
      - Severity level
      - Affected components
      - Remediation recommendations

      For results visit https://{{aap_domain}}/#/jobs/playbook/{{awx_job_id}}/output

      For questions or assistance, please contact the Security team.

      This is an automated message from the DevOps Vulnerability Management System.

    email_env_domain: "{{ ansible_domain }}"
    email_attachments:
    - "{{ processed_report }}"
    register: email_result

- name: Log email notification
  debug:
    msg: |
      Email notification details:
      - Sent to: {{ email_recipient }}
      - App Code: {{ app_code }}
      - Environment: {{ vault_environment | upper }}
      - Total issues: {{ total_vulnerabilities }}
      - High severity count: {{ high_severity_count }}
      - Issue Type: {{ current_issue_type }}
  when: report_stat.stat.exists and email_stat.stat.exists
