---
- name: IT Risk Metrics Email Notification
  hosts: localhost
  vars:
    # The survey_issue_type value is provided by the controller survey
    survey_issue_type: "{{ survey_issue_type_param | default('Vulnerability')}}"
    # Environment from the template values
    vault_env: "{{ vault_environment | default('DEV')}}"
    # HashiCorp Vault secrets path definitions
    secrets:
    - namespace: vault_credentials
      vault_env: "{{ vault_environment }}"
      vault_secret_path: "AAP/server_compliance_reporting/credentials"
    - namespace: vault_extravars
      vault_env: "{{ vault_environment }}"
      vault_secret_path: "AAP/server_compliance_reporting/extra_vars"

  roles:
    # HashiCorp Vault initialization role
    # Uncomment to use with actual vault
    # - role: rbc_common.hashicorp_vault.vault_init
    #   vars:
    #     survey_appcode: "{{ survey_appcode | default('ATU0')}}"
    #     vault_environment: "{{ vault_environment | default('DEV')}}"
    #     vault_environment:
    #       # Choose environment
    #       # - DEV
    #       # - QAT
    #       # - PROD

  tasks:
  - name: Assign secrets to dedicated variables
    ansible.builtin.set_fact:
      # These values would normally come from HashiCorp Vault
      es_service_id: "SATU0SRVECEWRITE"
      es_service_id_password: "R4@.iE@GmdVMp3"
    no_log: true

  - name: Assign extra vars to dedicated variables
    ansible.builtin.set_fact:
      # These values would normally come from HashiCorp Vault or the template 
      to: "feyi.sodipo@rbc.com"
      es_url: "https://e87a6cd02ed34b0b844d64cc7d8c41a9.ece.saifg.rbc.com:9243"
      server_compliance_metrics_index: "atu0-server-compliance-metrics"

  - name: Installing elastic module
    ansible.builtin.pip:
      name: elasticsearch
      # name: elasticsearch==8.17.2 if it fails
      state: present

  - name: Fetch data from Elasticsearch
    ansible.builtin.include_tasks: roles/tasks/fetch_data.yml
    vars:
      issue_type: "{{ survey_issue_type }}"
      raw_data_file: "roles/files/output/vulnerability_report_raw.json"

  - name: Process data and generate reports
    ansible.builtin.include_tasks: roles/tasks/process_data.yml
    vars:
      raw_data_file: "roles/files/output/vulnerability_report_raw.json"
      output_dir: "roles/files/output"
      role_path: "roles"

  - name: Loop through app codes and notify app custodian
    vars:
      vault_path: "AAP/server_compliance_reporting/extra_vars"
      raw_data_file: "roles/files/output/vulnerability_report_raw.json"
      output_dir: "roles/files/output"
      role_path: "roles"
    ansible.builtin.include_tasks: roles/tasks/notify_custodian.yml
